name: test

on:
  push:

jobs:
  qemu:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt update && sudo apt install qemu qemu-user
      - name: Checkout source
        uses: actions/checkout@v3
      - run: curl -o slirp4netns --fail -L https://github.com/rootless-containers/slirp4netns/releases/download/v1.2.0/slirp4netns-$(uname -m) && chmod +x slirp4netns
      - run: curl -o talos-amd64.iso --fail -L https://github.com/siderolabs/talos/releases/download/v1.0.5/talos-amd64.iso
      - run: /usr/bin/qemu-system-x86_64
      - run: ./runtest.sh
